const ADD_TASK = 'ADD_TASK';
const DELETE_TASK = 'DELETE_TASK';
const SEARCH_TASK = 'SEARCH_TASK';
const TOGGLE_CHECK_ALL_TASK = 'TOGGLE_CHECK_ALL_TASK';
const TOGGLE_CHECK_TASK = 'TOGGLE_CHECK_TASK';

const TOGGLE_DELETE_TASK_DIALOG = 'TOGGLE_DELETE_TASK_DIALOG';
const TOGGLE_ADD_TASK_DIALOG = 'TOGGLE_ADD_TASK_DIALOG';

const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

export {
  ADD_TASK,
  DELETE_TASK,
  SEARCH_TASK,
  TOGGLE_CHECK_ALL_TASK,
  TOGGLE_CHECK_TASK,
  TOGGLE_DELETE_TASK_DIALOG,
  TOGGLE_ADD_TASK_DIALOG,
  FETCH_CITIES_REQUEST,
  FETCH_CITIES_SUCCESS,
  FETCH_CITIES_FAILURE
};